version: "3.8"

services:
  kong-database:
    image: postgres:12
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpassword
    volumes:
      - kong-database:/var/lib/postgresql/data

  kong-migrations:
    image: kong:latest
    container_name: kong-migrations
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kongpassword"
    command: "kong migrations bootstrap"
    networks:
      - kong-network

  kong:
    image: kong:latest
    container_name: kong
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kongpassword"
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    ports:
      - "8000:8000" # Kong HTTP proxy
      - "8443:8443" # Kong HTTPS proxy
      - "8001:8001" # Kong Admin API
      - "8444:8444" # Kong Admin API over HTTPS (optional)
    networks:
      - kong-network

  konga:
    image: pantsel/konga
    container_name: konga
    depends_on:
      - kong-database
    environment:
      DB_ADAPTER: "postgres"
      DB_HOST: "kong-database"
      DB_USER: "kong"
      DB_PASSWORD: "kongpassword"
      DB_DATABASE: "kong"
      NODE_ENV: "production"
    ports:
      - "1337:1337" # Konga web UI
    networks:
      - kong-network

networks:
  kong-network:

volumes:
  kong-database:

