name: Kong Integration Test
on: push

env:
  KONG: 'localhost:8080'

jobs:
  # Label of the container job
  start_kong_container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start Kong Container
      run: sh ./scripts/kong-docker.sh

    - name: Install dependencies
      run: npm install
    
    - name: Wait container
      run: docker ps

    - name: Test the code
      run: npm run test

    - name: upload covarage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)


    