name: Kong Integration Test
on: push

env:
  KONG: 'localhost:8080'

jobs:
  # Label of the container job
  start_kong_container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start Kong Container
      run: |
        # Replace "docker-compose.yml" with the name of your Docker Compose file
        docker-compose -f docker-compose.yml up -d kong

    - name: Install dependencies
      run: npm install
    
    - name: Install dependencies
      run: npm run test

  